"""create order idempotency table

Revision ID: 888d01880253
Revises: 64eac7165d02
Create Date: 2026-08-16 09:57:59.333870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '888d01880253'
down_revision: Union[str, Sequence[str], None] = '64eac7165d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_idempotency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_order_idempotency_user_key')
    )
    op.create_index(op.f('ix_order_idempotency_id'), 'order_idempotency', ['id'], unique=False)
    op.create_index(op.f('ix_order_idempotency_order_id'), 'order_idempotency', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_idempotency_user_id'), 'order_idempotency', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_idempotency_user_id'), table_name='order_idempotency')
    op.drop_index(op.f('ix_order_idempotency_order_id'), table_name='order_idempotency')
    op.drop_index(op.f('ix_order_idempotency_id'), table_name='order_idempotency')
    op.drop_table('order_idempotency')
    # ### end Alembic commands ###
