"""add unique constraint to payment order_id

Revision ID: ded6f6e9e6d1
Revises: 4c29d3ce10e4
Create Date: 2026-09-20 20:39:29.209891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ded6f6e9e6d1'
down_revision: Union[str, Sequence[str], None] = '4c29d3ce10e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    # ### end Alembic commands ###
